### ISSUE TITLE
CDN imports in webpack

### ISSUE THREAD

**Issue by michielbdejong** [solid/meeting-pane#10]
We should tell our various webpack configs to fetch rdflib.js and solid-ui from cdn, see https://webpack.js.org/configuration/externals/. That way if you have used e.g. chat.inrupt.app or michielbdejong.inrupt.net before, your browser will have cached those and loading meetulator.inrupt.app will be faster.

**Comment by RubenVerborgh** [comment]
This is an interesting one. Such externalization during compile time can be seen as a first step to modularization. We shouldn't do this lightly (in the long term), as it involves questions regarding versioning etc.

The use of a specific CDN would also reach concerns regarding centralization, both from a security perspective and from a single point of failure. Strategically, we don't want people to think that we are tracking them (which is a goal of some CDNs). Maybe people even want a CDN preference in their profile. We probably always want an app-local fallback as well in case the CDN fails or is (user-)blocked.

In the longer term, we could even imagine a browser extension that controls the loading of such external dependencies and keeps a local cache. I'm especially interested in on-demand loading, such that only the JS that is needed at a certain point is cached.

**Comment by michielbdejong** [comment]
Closed this because of the concerns Ruben raised.
