### ISSUE TITLE
Google Doc as meeting material, iframing makes it unreadable

### ISSUE THREAD

**Issue by michielbdejong** [solid/meeting-pane#12]

**Comment by michielbdejong** [comment]
See https://michielbdejong.inrupt.net/public/example-meeting/index.ttl#this for an example

![Screenshot 2020-01-03 13 48 13](https://user-images.githubusercontent.com/408412/71724197-b730f100-2e2f-11ea-8dbe-28b89d2f14ae.png)

**Comment by timbl** [comment]
You mean the iframe is too small? It should have a drag handle to make it bigger in your local view.  Maybe the resize doesn't work in FF

**Comment by timbl** [comment]
![image](https://user-images.githubusercontent.com/1254848/72001518-a4456480-3213-11ea-9d5f-df8d2fd23355.png)
Works in Chrome

**Comment by michielbdejong** [comment]
Ah found it now, great!

@kevin-howard-jd is/will this mentioned in the user guide? It wasn't obvious to me.

**Comment by kevin-howard-jd** [comment]
There is no specific section in the userguide about adding other resources to a meeting, just a reference to dragging URLs to the tool bar. We can expand upon it.

**Comment by kevin-howard-jd** [comment]
Added to the userguide: https://github.com/solid/userguide/pull/14

**Comment by timbl** [comment]
Fixes to the tab bodies  filling the space are in https://github.com/solid/solid-ui/pull/185 and in https://github.com/solid/meeting-pane/pull/29

**Comment by megoth** [comment]
As both https://github.com/solid/solid-ui/pull/185 and https://github.com/solid/meeting-pane/pull/29 are merged, I'll close this issue.
