### ISSUE TITLE
Allow user to control which tab is the default  others see when loading the meeting

### ISSUE THREAD

**Issue by timbl** [solid/meeting-pane#20]
Having the metadata table for the meeting as the default is often not what you want.   Specifically, if there is a chat that should typically be the default tab.  If there is unfinished poll, that should take precedence by default, but the users should always be able to change it.

Could - change the default; could - change the order and always make the first one the default.

**Comment by timbl** [comment]
duplicate

**Comment by michielbdejong** [comment]
of #19
