### ISSUE TITLE
Latest version breaks solid-panes build

### ISSUE THREAD

**Issue by michielbdejong** [solid/meeting-pane#31]
The latest version (2.0.5) was distributed unbuilt.

Since this code is now transpiled, the package needs an `npm prepublish` step. Sorry, I should have added that the package.json as part of adding the transpilation. Will fix in 2.0.6, as a workaround for the time being, to allow solid-panes development to continue, solid-panes can require version 2.0.0 until meeting-pane@2.0.6 becomes available.

**Comment by michielbdejong** [comment]
I think this is now fixed, testing in https://github.com/solid/solid-panes/pull/224

**Comment by megoth** [comment]
Have you verified the fix, and can this issue be closed?

**Comment by michielbdejong** [comment]
Yep! Thanks.
